install:
  - sudo apt-get update
  - sudo apt-get install libqt4-dev qt4-qmake

script:
  - wget https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-gpu-linux-x86_64-1.12.0.tar.gz
  - ls
  - sudo tar -xz libtensorflow-gpu-linux-x86_64-1.12.0.tar.gz -C tensorflow
  - sudo ldconfig
  - qmake -project
  - qmake tf2ovx.pro
  - make
